### ISSUE TITLE
Instructions clarification

### ISSUE THREAD

**Issue by micah** [vbehar/openshift-git#2]
Hi, in the whole cluster setup you say:

```
give the cluster-reader role to the newly created service account:

oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:$(oc project -q):git-exporter
```

I'm not understanding why there is the `oc project -q` in there. This is going to return the current project that you are on. Isn't the service account supposed to be cluster-wide, and not scoped to a specific project?

**Comment by vbehar** [comment]
Hi,

that's because service-accounts are namespaced. so the full name of your service-acccount will include the project name (even if this SA has a cluster-wide role).

you are maybe confused because openshift always create a few service-accounts with the same names in all projects (default, deployer, builder, ...)

**Comment by micah** [comment]
Thanks for the reply!

> that's because service-accounts are namespaced. so the full name of
> your service-acccount will include the project name (even if this SA
> has a cluster-wide role).

Yeah, but what I don't understand is *which* project name? If its going
to be a cluster-wide role, do I put it in the 'default' project? Or are
you saying that it doesn't matter what project I do it in? If that is
true, what happens if that project is removed?

> you are maybe confused because openshift always create a few
> service-accounts with the same names in all projects (default,
> deployer, builder, ...)

I am indeed confused by this!

**Comment by vbehar** [comment]
Yes, the project doesn't matter. And if the project is deleted, the service account will be deleted too.
I recommend you to put the service account in the same project as the pod.

**Comment by micah** [comment]
thanks!
